server:
  port: 8084
  servlet:
    context-path: /api
spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notes
    username: root
    password: pass
  liquibase:
    change-log: classpath:db_changelog/master.yml
