spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notes
    username: root
    password: pass
    initialize-samples: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false