spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notes
    username: admin
    password: admin
    initialize-samples: false
  liquibase:
    change-log: classpath:db_changelog/master-test.yml
