spring:
  datasource:
    url: jdbc:mysql://nmysql:3306/notes
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db_changelog/master.yml
    enabled: true